<a href="https://colab.research.google.com/github/lacerdamj/Sistemas-Lineares/blob/main/Representa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sistemas Lineares**
# Representação entrada saída e representação em espaço de estados

*Escrito por Márcio J. Lacerda*

In [ ]:
#Importando as bibliotecas
import numpy as np
import scipy
!pip install control
import control


Considere o seguinte sistema contínuo no tempo, representado em espaço de estados:

$$
\dot{x}=\begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ -4 &-3 &-2 \end{bmatrix}x+
\begin{bmatrix} 0  \\ 0  \\ 1 \end{bmatrix}u,
$$
com saída
$$
y= \begin{bmatrix} -1 & 2 & 1 \end{bmatrix}x.
$$

Encontre  a representação entrada-saída, ou seja, a função de transferência do sistema.

In [40]:
#Primeiro passo, descrever as matrizes da representação em espaço de estados
A = [[0,1,0], [0,0,1],[-4,-3,-2]]
B = [[0], [0],[1]]
C = [[-1, 2,1]]
D = [[0]]

#Usar a função control.ss2tf (state space to transfer function).
sys1 = control.ss2tf(A, B, C, D)

#Mostra a resposta obtida
print("A função de transferência é",sys1)

A função de transferência é 
    s^2 + 2 s - 1
---------------------
s^3 + 2 s^2 + 3 s + 4



O mesmo procedimento pode ser realizado de outra forma, como apresentado no seguinte código:

In [41]:
#Primeiro passo, descrever o sistema em espaço de estados
sys_ss = control.ss(A, B, C, D)
print("Representação em espaço de estados:",sys_ss)

#Usar a função control.ss2tf (state space to transfer function).
sys2 = control.ss2tf(sys_ss)
print("A função de transferência é", sys2)

Representação em espaço de estados: <LinearIOSystem>: sys[49]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ 0.  1.  0.]
     [ 0.  0.  1.]
     [-4. -3. -2.]]

B = [[0.]
     [0.]
     [1.]]

C = [[-1.  2.  1.]]

D = [[0.]]

A função de transferência é 
    s^2 + 2 s - 1
---------------------
s^3 + 2 s^2 + 3 s + 4



A partir da função de transferência obtida no passo anterior:

$$
G(s)=\frac{s^2+2s-1}{s^3+2s^2+3s+4}.
$$

Obtenha uma nova realização em espaço de estados. 

In [42]:
#Defina o vetor com os coeficientes do numerador da função de transferência
num=[1,2,-1]
#Defina o vetor com os coeficientes do denominador da função de transferência
den=[1,2,3,4]

#Usar a função control.tf2ss (transfer function to state space).
sys3 = control.tf2ss(num, den)
print("Matrizes da representação em espaço de estados:", sys3)

Matrizes da representação em espaço de estados: A = [[-2. -3. -4.]
     [ 1.  0.  0.]
     [ 0.  1.  0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[ 1.  2. -1.]]

D = [[0.]]



Outra forma de solucionar o problema é apresentada a seguir:

In [43]:
#Primeiro passo, descrever o sistema na forma entrada saída.
sys_tf = control.tf(num, den)
print("A função de transferência é", sys_tf)

#Usar a função control.tf2ss (transfer function to state space).
sys4 = control.tf2ss(sys_tf)
print("Matrizes da representação em espaço de estados:",sys4)

A função de transferência é 
    s^2 + 2 s - 1
---------------------
s^3 + 2 s^2 + 3 s + 4

Matrizes da representação em espaço de estados: A = [[-2. -3. -4.]
     [ 1.  0.  0.]
     [ 0.  1.  0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[ 1.  2. -1.]]

D = [[0.]]



Note que a representação em espaço de estados obtida é diferente daquela apresentada no início do problema. 


$$
\dot{x}=\begin{bmatrix} -2 & -3 & -4 \\ 1 & 0 & 0 \\ 0 &1 &0 \end{bmatrix}x+
\begin{bmatrix} 1  \\ 0  \\ 0 \end{bmatrix}u,
$$
com saída
$$
y= \begin{bmatrix} 1 & 2 & -1 \end{bmatrix}x.
$$



De fato, um mesmo sistema possui diferentes realizações. Entretanto, todas as realizações levam à mesma função de transferência. Para confirmar este fato, vamos obter a representação entrada saída a partir da representação em espaço de estados obtida anteriormente.

In [44]:
#Aplicando o comando no sistema 4 (em espaço de estados) obtido anteriormente.
sys5=control.ss2tf(sys4)

#Apresentadndo a resposta
print("A função de transferência é: ",sys5)

A função de transferência é:  
    s^2 + 2 s - 1
---------------------
s^3 + 2 s^2 + 3 s + 4



Observe que a função de transferência para um mesmo sistema não se altera.  